name: Deploy Docker Compose

on:
  push:
    branches:
      - main  # 当推送到 main 分支时触发

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2


    - name: Set up Docker Compose
      run: sudo apt-get update && sudo apt-get install -y docker-compose

    - name: Build and push Docker images
      run: |
        docker-compose -f docker-compose.yml build
        docker-compose -f docker-compose.yml push

    - name: Deploy with Docker Compose
      run: |
        docker-compose -f docker-compose.yml pull
        docker-compose -f docker-compose.yml up -d
        docker exec -it mongo /bin/bash
        
        sleep 300  # 5分钟
        docker-compose -f docker-compose.yml down
